// <auto-generated />
using System;
using DatabaseHandler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseHandler.Migrations
{
    [DbContext(typeof(FysioDataContext))]
    partial class FysioDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DatabaseHandler.Models.ActionPlan", b =>
                {
                    b.Property<int>("ActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("TimePerSession")
                        .HasColumnType("int");

                    b.HasKey("ActionID");

                    b.ToTable("ActionPlans");
                });

            modelBuilder.Entity("DatabaseHandler.Models.Adress", b =>
                {
                    b.Property<int>("AdressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdressID");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("DatabaseHandler.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CommentMadeByFysioWorkerID")
                        .HasColumnType("int");

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommenterID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateMade")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PatientFileID")
                        .HasColumnType("int");

                    b.Property<bool>("VisibleToPatient")
                        .HasColumnType("bit");

                    b.HasKey("CommentId");

                    b.HasIndex("CommentMadeByFysioWorkerID");

                    b.HasIndex("PatientFileID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DatabaseHandler.Models.FysioWorker", b =>
                {
                    b.Property<int>("FysioWorkerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BIGNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FysioWorkerID");

                    b.ToTable("FysioWorkers");
                });

            modelBuilder.Entity("DatabaseHandler.Models.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdressID")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnsuranceCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientID");

                    b.HasIndex("AdressID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("DatabaseHandler.Models.PatientFile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentIDs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdactionPlan")
                        .HasColumnType("int");

                    b.Property<int?>("IdintakeSuppervisedBy")
                        .HasColumnType("int");

                    b.Property<int>("IdmainTherapist")
                        .HasColumnType("int");

                    b.Property<int?>("actionPlanActionID")
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("diagnoseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diagnoseCodeComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("intakeDoneByID")
                        .HasColumnType("int");

                    b.Property<int?>("intakeSuppervisedByFysioWorkerID")
                        .HasColumnType("int");

                    b.Property<bool>("isStudent")
                        .HasColumnType("bit");

                    b.Property<string>("issueDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("mainTherapistFysioWorkerID")
                        .HasColumnType("int");

                    b.Property<int>("patientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("sessionIDs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("actionPlanActionID");

                    b.HasIndex("intakeDoneByID");

                    b.HasIndex("intakeSuppervisedByFysioWorkerID");

                    b.HasIndex("mainTherapistFysioWorkerID");

                    b.HasIndex("patientID");

                    b.ToTable("PatientFiles");
                });

            modelBuilder.Entity("DatabaseHandler.Models.TherapySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPractiseRoom")
                        .HasColumnType("bit");

                    b.Property<int?>("PatientFileID")
                        .HasColumnType("int");

                    b.Property<int?>("SesionDoneByFysioWorkerID")
                        .HasColumnType("int");

                    b.Property<int>("SessionDoneByID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SessionStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientFileID");

                    b.HasIndex("SesionDoneByFysioWorkerID");

                    b.ToTable("TherapySessions");
                });

            modelBuilder.Entity("DatabaseHandler.Models.Comment", b =>
                {
                    b.HasOne("DatabaseHandler.Models.FysioWorker", "CommentMadeBy")
                        .WithMany()
                        .HasForeignKey("CommentMadeByFysioWorkerID");

                    b.HasOne("DatabaseHandler.Models.PatientFile", null)
                        .WithMany("comments")
                        .HasForeignKey("PatientFileID");

                    b.Navigation("CommentMadeBy");
                });

            modelBuilder.Entity("DatabaseHandler.Models.Patient", b =>
                {
                    b.HasOne("DatabaseHandler.Models.Adress", "Adress")
                        .WithMany()
                        .HasForeignKey("AdressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adress");
                });

            modelBuilder.Entity("DatabaseHandler.Models.PatientFile", b =>
                {
                    b.HasOne("DatabaseHandler.Models.ActionPlan", "actionPlan")
                        .WithMany()
                        .HasForeignKey("actionPlanActionID");

                    b.HasOne("DatabaseHandler.Models.FysioWorker", "intakeDoneBy")
                        .WithMany()
                        .HasForeignKey("intakeDoneByID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseHandler.Models.FysioWorker", "intakeSuppervisedBy")
                        .WithMany()
                        .HasForeignKey("intakeSuppervisedByFysioWorkerID");

                    b.HasOne("DatabaseHandler.Models.FysioWorker", "mainTherapist")
                        .WithMany()
                        .HasForeignKey("mainTherapistFysioWorkerID");

                    b.HasOne("DatabaseHandler.Models.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("patientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("actionPlan");

                    b.Navigation("intakeDoneBy");

                    b.Navigation("intakeSuppervisedBy");

                    b.Navigation("mainTherapist");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("DatabaseHandler.Models.TherapySession", b =>
                {
                    b.HasOne("DatabaseHandler.Models.PatientFile", null)
                        .WithMany("sessions")
                        .HasForeignKey("PatientFileID");

                    b.HasOne("DatabaseHandler.Models.FysioWorker", "SesionDoneBy")
                        .WithMany()
                        .HasForeignKey("SesionDoneByFysioWorkerID");

                    b.Navigation("SesionDoneBy");
                });

            modelBuilder.Entity("DatabaseHandler.Models.PatientFile", b =>
                {
                    b.Navigation("comments");

                    b.Navigation("sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
